# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MLNetworking' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MLNetworking
  pod 'MLNetworking', :path => './'
  #pod 'ProgressHUD', :git => 'https://github.com/relatedcode/ProgressHUD.git'


  target 'MLNetworkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MLNetworkingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
