# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CuentaBancariaUI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for CuentaBancariaUI
  pod 'CuentaBancariaLIB', :path => '../CuentaBancariaLIB/'
  target 'CuentaBancariaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CuentaBancariaUIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
