# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cuenta-bancaria' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 use_frameworks!

  # Pods for cuenta-bancaria
  pod 'CuentaBancariaLib', :path => "../cuenta-bancaria-lib/"

  target 'cuenta-bancariaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cuenta-bancariaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
