# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IosAcelerator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IosAcelerator
  pod 'MLNetworking', :path => '../MLNetworking/'
  #pod 'ProgressHUD', :git => 'https://github.com/relatedcode/ProgressHUD.git'

  target 'IosAceleratorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IosAceleratorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
