# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'practico-3-iswifttunes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'MELINetworking', :path => "../pod-networking"
  pod 'ProgressHUD', :git => "https://github.com/relatedcode/ProgressHUD.git"

  # Pods for practico-3-iswifttunes

end
